package uz.dilshodlatipov.secretsguard.service;

import uz.dilshodlatipov.secretsguard.config.SecretsGuardProperties;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.time.Instant;
import java.util.EnumSet;
import java.util.Set;

public class GitHookService {

    private final SecretsGuardProperties properties;

    public GitHookService(SecretsGuardProperties properties) {
        this.properties = properties;
    }

    public boolean isAlreadyInitialized(Path repoRoot) {
        Path hooksDir = repoRoot.resolve(".git").resolve("hooks");
        Path hookFile = hooksDir.resolve("pre-commit");
        if (!Files.exists(hookFile)) {
            return false;
        }
        try {
            String content = Files.readString(hookFile);
            return content.contains("Generated by secrets-guard");
        } catch (IOException ex) {
            return false;
        }
    }

    public Path installPreCommitHook(Path repoRoot) {
        Path hooksDir = repoRoot.resolve(".git").resolve("hooks");
        if (!Files.exists(hooksDir)) {
            throw new IllegalStateException("No .git/hooks directory found at " + hooksDir);
        }
        Path hookFile = hooksDir.resolve("pre-commit");
        if (Files.exists(hookFile)) {
            throw new IllegalStateException("pre-commit hook already exists at " + hookFile);
        }
        String script = "#!/bin/sh\n" +
                "# Generated by secrets-guard\n" +
                "# Created: " + Instant.now() + "\n" +
                properties.getHooks().getPreCommitCommand() + "\n";
        try {
            Files.writeString(hookFile, script);
            setExecutable(hookFile);
            return hookFile;
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to write git hook", ex);
        }
    }

    private void setExecutable(Path hookFile) throws IOException {
        try {
            Set<PosixFilePermission> perms = EnumSet.of(
                    PosixFilePermission.OWNER_READ,
                    PosixFilePermission.OWNER_WRITE,
                    PosixFilePermission.OWNER_EXECUTE,
                    PosixFilePermission.GROUP_READ,
                    PosixFilePermission.GROUP_EXECUTE
            );
            Files.setPosixFilePermissions(hookFile, perms);
        } catch (UnsupportedOperationException ex) {
            hookFile.toFile().setExecutable(true);
        }
    }
}
